In [3]:
import pandas as pd
from datasets import Dataset as hf_dataset

In [4]:
translation_data_path = "/media/shaswata/4TB_1/Projects/transformer_umar/pytorch-transformer/data/dataset/en-bn.csv"
ds_df = pd.read_csv(translation_data_path)
ds_raw = hf_dataset.from_pandas(ds_df)

In [6]:
ds_df.head()

,english_caption,bengali_caption
0,a child in a pink dress is climbing up a set o...,একটি গোলাপী জামা পরা বাচ্চা মেয়ে একটি বাড়ির প্...
1,a girl going into a wooden building .,একটি মেয়ে শিশু একটি কাঠের বাড়িতে ঢুকছে
2,a little girl climbing into a wooden playhouse .,একটি বাচ্চা তার কাঠের খেলাঘরে উঠছে ।
3,a little girl climbing the stairs to her playh...,ছোট মেয়েটি তার খেলার ঘরের সিড়ি বেয়ে উঠছে
4,a little girl in a pink dress going into a woo...,গোলাপি জামা পড়া ছোট একটি মেয়ে একটি কাঠের তৈরি...

In [5]:
ds_raw

Dataset({
    features: ['english_caption', 'bengali_caption'],
    num_rows: 39065
})

## {'id': '0', 'translation': {'en': 'Source: Project Gutenberg', 'it': 'Source: www.liberliber.it/Audiobook available here'}}

In [11]:
translation_list = []

en_list = ds_df['english_caption'].to_list()
bn_list = ds_df['bengali_caption'].to_list()

size = len(en_list)

if len(en_list) == len(bn_list):
    for i in range(size):
        tmp = {
            'en': en_list[i],
            'bn': bn_list[i]
        }
        translation_list.append(tmp)

In [13]:
id_list = list(range(size))

In [12]:
translation_list[:2]

[{'en': 'a child in a pink dress is climbing up a set of stairs in an entry way .',
  'bn': 'একটি গোলাপী জামা পরা বাচ্চা মেয়ে একটি বাড়ির প্রবেশ পথের সিঁড়ি বেয়ে উঠছে।'},
 {'en': 'a girl going into a wooden building .',
  'bn': 'একটি মেয়ে শিশু একটি কাঠের বাড়িতে ঢুকছে'}]

In [14]:
id_list[:2]

[0, 1]

In [15]:
print(size)

39065

In [16]:
ds_dict = {
    'id': id_list,
    'translation': translation_list
}

In [17]:
ds_df = pd.DataFrame(ds_dict)

In [22]:
ds_df.head()

   id                                        translation
0   0  {'en': 'a child in a pink dress is climbing up...
1   1  {'en': 'a girl going into a wooden building .'...
2   2  {'en': 'a little girl climbing into a wooden p...
3   3  {'en': 'a little girl climbing the stairs to h...
4   4  {'en': 'a little girl in a pink dress going in...

In [20]:
ds_df.to_csv("/media/shaswata/4TB_1/Projects/transformer_umar/pytorch-transformer/data/dataset/en-bn.csv")